import libs += pugixml%lib{pugixml}
import libs += libboost-program-options%lib{boost_program_options}
import libs += libboost-json%lib{boost_json}

exe{comet-html}: {hxx ixx txx cxx}{**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"
